### ISSUE TITLE
Register?

### ISSUE THREAD

**Issue by avik-pal** [JuliaGPU/NCCL.jl#50]
It seems like NCCL has been functional for a month now. Is there a plan/timeline to register it?

**Comment by maleadt** [comment]
@simonbyrne You revived this package; anything you want in before registering?

**Comment by simonbyrne** [comment]
No, I'm happy with it now. Please go ahead and register it.

**Comment by maleadt** [comment]
OK, I'll register and tag v0.1. The current interface seems pretty clunky still (closely following the C one), but I guess this is fine for a first release.

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/101425
